# Generated by Django 3.1.7 on 2021-05-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesOfDishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesOfIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование категории')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование продукта')),
                ('categoryOfIngredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.categoriesofingredients', verbose_name='Наименование категории ингредиента')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Наименование блюда')),
                ('describe', models.CharField(max_length=2048, verbose_name='Описание')),
                ('timeOfCooking', models.CharField(max_length=32, verbose_name='Время приготовления')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('picture', models.CharField(blank=True, max_length=512, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('dishCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.categoriesofdishes', verbose_name='Наименование категории блюда')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=10, verbose_name='Пароль')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepOfCooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(blank=True, max_length=512, null=True)),
                ('step', models.IntegerField(verbose_name='Номер шага')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование шага')),
                ('describe', models.CharField(max_length=512, verbose_name='Описание шага')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipes', verbose_name='Шаги приготовления в рецепте')),
            ],
        ),
        migrations.CreateModel(
            name='recipesIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=64, verbose_name='Количество грамм ингредиента')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.ingredients', verbose_name='Ингредиенты в рецепте')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipes', verbose_name='Id Рецепта')),
            ],
        ),
        migrations.AddField(
            model_name='recipes',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, to='base.Users', verbose_name='Сохраненный рецепт'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='base.users', verbose_name='Автор рецепта'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='Текст')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipes', verbose_name='Комментарий к рецепту')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.users', verbose_name='Автор комментария')),
            ],
        ),
    ]
