# Generated by Django 3.1.7 on 2021-03-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=512, verbose_name='Описание')),
                ('timeOfCooking', models.IntegerField()),
                ('rating', models.ImageField(max_length=5, upload_to='')),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('photo', models.ImageField(upload_to='')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepOfCooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='Номер шага')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование шага')),
                ('describe', models.CharField(max_length=512, verbose_name='Описание шага')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipes', verbose_name='Шаги приготовления в рецепте')),
            ],
        ),
        migrations.AddField(
            model_name='recipes',
            name='favourites',
            field=models.ManyToManyField(to='base.User', verbose_name='Сохраненный рецепт'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(to='base.Ingredients', verbose_name='Ингредиенты в рецепте'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='base.user', verbose_name='Автор рецепта'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='Текст')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipes', verbose_name='Комментарий к рецепту')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user', verbose_name='Автор комментария')),
            ],
        ),
    ]
