# Generated by Django 3.1.7 on 2021-04-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210426_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
