# Generated by Django 3.1.7 on 2021-05-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210502_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=10, verbose_name='Пароль'),
        ),
    ]
