# Generated by Django 3.1.7 on 2021-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210503_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
