# Generated by Django 3.1.7 on 2021-05-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210504_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='categoryOfIngredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.categoriesofingredients', verbose_name='Наименование категории ингредиента'),
        ),
    ]
